### ISSUE TITLE
Mobile toolbar is not respected

### ISSUE THREAD

**Issue by LumenYoung** [mschmidtkorth/silverbullet-zen#1]
Hi, I just found the following problem with the theme:

![Image](https://github.com/user-attachments/assets/31d10465-e347-4572-8fb3-a7fb5c339dc9)

I've setted the `mobileMenuStyle = "bottom-bar"` which could be the source of the issue (in fact I get non-overlapping rendering of the top when turn this to `top-bar`. Could we have support for bottom-bar?

**Comment by emadalam** [comment]
Add the following to support `mobileMenuStyle = "bottom-bar"`.

```css
@media only screen and (max-width: 600px) {
  #sb-top {
    opacity: 1;

    & .sb-actions.bottom-bar {
      bottom: calc(-100vh + 55px);
      background-color: var(--top-background-color);

      & button {
        background-color: var(--top-background-color);
      }
    }
  }

  .sb-bhs {
    margin-bottom: 60px;
  }
}
```

Also fix the color variable `--surface-lower` to include `rgb`.

```css
html[data-theme="dark"] {
  /* Theme colors */
  ...
  --surface-lower: rgb(28, 28, 28);
}
```
